### ISSUE TITLE
[Feature Request] Don't show chest if it can't be lockpicked

### ISSUE THREAD

**Issue by scalp42** [Jassade/CanOpener#28]
Hi @Jassade,

Thank you so much for the addon!

I'd love if it could handle the situation where you have a chest that  can't opened due to missing the lockpick requirements.

Cheers,

Anthony (the best name right? 😂)

**Comment by Jassade** [comment]
I have temporarily disabled (earlier today) the lockpick feature and lockboxs should no longer appear in the button bar. I am working on another angle to handle lockpicking in a more robust way.

I am glad you are enjoying the addon. If you have any other suggestions feel free to open another issue, or try your hand at making the modifications and submitting a pull request.

Thank you, and I agree that Anthony is a great name 😉

**Comment by scalp42** [comment]
Thank you again!

I'm actually going to take a look at your code as the scope of it should make it easier to get into writing WoW addons. One of the biggest difficulties I have is that it's not 100% clear where to find the methods/function you're using, the "official" WoW UI API if it makes sense, happy to get feedback.

I'll close for now, cheers.
